version: '2'

services:
  flask:
    build:
      context: "."
    ports:
        - "8000:5000"
    environment:
      - FLASK_APP=app
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - FLASK_LOGGING_LEVEL=DEBUG
      - FLASK_REDIS_HOST=redis
      - FLASK_REDIS_PASSWORD=123456
      - FLASK_REDIS_PORT=6379
    depends_on:
      - redis
  redis:
    image: 'redis'
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD}"
    ports:
      - "6370:6379"
    environment:
      - REDIS_PASSWORD=123456